import { Translation } from '../types'

export const hi: Translation = {
  title: 'सोशल मीडिया कार्ड जेनरेटर',
  subtitle: 'पेशेवर सोशल कार्ड डिज़ाइन टूल',
  description: 'विभिन्न थीम और कस्टम सामग्री के साथ सुंदर सोशल मीडिया कार्ड बनाएं',
  nav: { editContent: 'सामग्री संपादित करें', finishEdit: 'संपादन समाप्त करें', generateImage: 'छवि बनाएं', generating: 'बना रहे हैं...', horizontal: 'क्षैतिज', vertical: 'लंबवत', editMode: 'संपादन मोड' },
  themes: { blue: 'व्यावसायिक नीला', green: 'प्राकृतिक हरा', purple: 'रचनात्मक बैंगनी', orange: 'ऊर्जावान नारंगी', pink: 'सुंदर गुलाबी', dark: 'आधुनिक गहरा' },
  content: { name: 'नाम', title: 'शीर्षक', company: 'कंपनी', phone: 'फोन', email: 'ईमेल', website: 'वेबसाइट', wechat: 'WeChat', bio: 'जीवनी', uploadQR: 'QR अपलोड करें', features: 'विशेषताएं' },
  ui: { selectTheme: 'थीम चुनें', layoutMode: 'लेआउट मोड', previewEffect: 'पूर्वावलोकन प्रभाव', collapsePreview: 'पूर्वावलोकन छोटा करें', expandPreview: 'पूर्वावलोकन बड़ा करें', completeEditFirst: 'कृपया छवि बनाने से पहले संपादन पूरा करें या पूर्वावलोकन का विस्तार करें', share: 'साझा करें', shareToSocialMedia: 'सोशल मीडिया पर साझा करें', copied: 'कॉपी हो गया!', copyLink: 'लिंक कॉपी करें', email: 'ईमेल', cardNotFound: 'कार्ड तत्व नहीं मिला, कृपया फिर से कोशिश करें', generateImageFailed: 'छवि बनाना असफल, कृपया फिर से कोशिश करें', selectValidImageFile: 'कृपया एक वैध छवि फ़ाइल चुनें' },
  footer: { developer: 'द्वारा विकसित', githubRepo: 'GitHub रिपॉजिटरी', addAuthorWechat: 'लेखक WeChat जोड़ें', wechatPublic: 'WeChat सार्वजनिक खाता', scanToFollow: 'फॉलो करने के लिए स्कैन करें', scanToAdd: 'जोड़ने के लिए स्कैन करें', clickToEnlarge: 'बड़ा करने के लिए टैप करें', hoverToEnlarge: 'बड़ा करने के लिए होवर करें', websiteInfo: 'वेबसाइट जानकारी', domain: 'www.sm-card.com', websiteDescription: 'सोशल मीडिया कार्ड जेनरेटर' },
  defaultContent: { title: 'Full-Stack डेवलपर', subtitle: 'प्रौद्योगिकी समाधान विशेषज्ञ', description: 'आधुनिक प्रौद्योगिकियों में विशेषज्ञता रखने वाले जुनूनी डेवलपर, वेब और मोबाइल ऐप विकास में समृद्ध अनुभव के साथ', feature1: 'प्रीमियम कम्युनिटी सेवा €1.4', feature2: 'कार्यालय स्वचालन €42 से', feature3: 'सॉफ़्टवेयर अनुकूलन सेवा बातचीत योग्य', feature4: 'व्यावसायिक परिवर्तन परामर्श €140 से' },
  meta: { title: 'सोशल मीडिया कार्ड जेनरेटर - पेशेवर डिज़ाइन टूल', description: 'मुफ्त सोशल मीडिया कार्ड जेनरेटर जिसमें कई थीम, ड्रैग-एंड-ड्रॉप सॉर्टिंग, रियल-टाइम पूर्वावलोकन और एक-क्लिक उच्च गुणवत्ता कार्ड जनरेशन है', keywords: 'सोशल मीडिया कार्ड,कार्ड जेनरेटर,सामाजिक कार्ड,कार्ड डिज़ाइन,कार्ड मेकर,ऑनलाइन कार्ड मेकर' },
  seo: {
    common: { backToHome: 'होम पर वापस जाएं', lastUpdated: 'अंतिम अपडेट', getStarted: 'शुरू करें', learnMore: 'और जानें', readyToStart: 'शुरू करने के लिए तैयार?', startCreating: 'अब बनाना शुरू करें', quickStart: 'त्वरित शुरुआत', tipsAndTricks: 'टिप्स और ट्रिक्स', bestPractices: 'सर्वोत्तम प्रथाएं', commonFeatures: 'सामान्य विशेषताएं', stillHaveQuestions: 'अभी भी प्रश्न हैं?', contactSupport: 'सहायता से संपर्क करें', followUs: 'हमें फॉलो करें', openSource: 'ओपन सोर्स', projectIntroduction: 'परियोजना परिचय', ourMission: 'हमारा मिशन', features: 'विशेषताएं', technologyStack: 'प्रौद्योगिकी स्टैक', developmentTeam: 'विकास टीम', contactUs: 'हमसे संपर्क करें', websiteInfo: 'वेबसाइट जानकारी', legalNotice: 'कानूनी सूचना', dataProcessingDetails: 'डेटा प्रसंस्करण विवरण', userRights: 'आपके अधिकार', disclaimer: 'अस्वीकरण', legalJurisdiction: 'कानूनी न्यायाधिकार', termsQuestions: 'नियमों के बारे में प्रश्न?', privacyQuestions: 'गोपनीयता प्रश्न?', supportChannels: 'सहायता चैनल' },
    navigation: { about: 'हमारे बारे में', faq: 'FAQ', guide: 'उपयोगकर्ता गाइड', privacy: 'गोपनीयता नीति', terms: 'सेवा की शर्तें', contact: 'संपर्क करें', sitemap: 'साइटमैप' },
    about: { title: 'सोशल मीडिया कार्ड जेनरेटर के बारे में', description: 'हमारे मिशन, टीम और प्रौद्योगिकी के बारे में जानें', content: { introduction: 'उच्च गुणवत्ता वाले सोशल मीडिया कार्ड बनाने के लिए पेशेवर ऑनलाइन टूल।', mission: 'सभी को आसानी से पेशेवर और सुंदर कार्ड बनाने में सक्षम बनाना।', features: 'कई थीम स्टाइल, ड्रैग-एंड-ड्रॉप, रियल-टाइम पूर्वावलोकन।', technology: 'Next.js, React, TypeScript और Tailwind CSS के साथ बनाया गया।', team: 'अनुभवी डेवलपर्स और डिज़ाइनरों की टीम।', contact: 'प्रश्न या सुझावों के लिए हमसे संपर्क करें।' } },
    faq: { title: 'अक्सर पूछे जाने वाले प्रश्न', description: 'कार्ड जेनरेटर के बारे में सामान्य प्रश्न', questions: { q1: { question: 'जेनरेटर का उपयोग कैसे करें?', answer: 'थीम चुनें, जानकारी भरें, मॉड्यूल खींचें, पूर्वावलोकन करें और बनाएं।' }, q2: { question: 'कौन सी भाषाएं समर्थित हैं?', answer: 'हिंदी, अंग्रेजी, चीनी, जापानी आदि सहित 20+ भाषाएं।' }, q3: { question: 'व्यावसायिक उपयोग संभव?', answer: 'हाँ, व्यक्तिगत और व्यावसायिक उपयोग के लिए पूर्णतः निःशुल्क।' }, q4: { question: 'QR कोड कैसे बदलें?', answer: 'संपादित करें, QR अपलोड क्षेत्र खोजें, नई छवि अपलोड करें।' }, q5: { question: 'छवि गुणवत्ता?', answer: 'उच्च रिज़ॉल्यूशन, पारदर्शी पृष्ठभूमि के साथ PNG प्रारूप।' }, q6: { question: 'पंजीकरण आवश्यक?', answer: 'नहीं, बिना पंजीकरण की आवश्यकता के निःशुल्क सेवा।' }, q7: { question: 'डेटा सुरक्षा?', answer: 'आपके ब्राउज़र में स्थानीय प्रसंस्करण, अधिकतम गोपनीयता।' }, q8: { question: 'तकनीकी सहायता?', answer: 'WeChat: skingko या GitHub के माध्यम से संपर्क करें।' } } },
    guide: { title: 'उपयोगकर्ता गाइड', description: 'सभी सुविधाओं का उपयोग करना सीखें', steps: { step1: { title: 'थीम चुनें', content: 'कई सुंदर शैलियों में से चुनें।' }, step2: { title: 'जानकारी भरें', content: 'अपनी व्यक्तिगत और संपर्क जानकारी दर्ज करें।' }, step3: { title: 'अनुकूलित करें', content: 'लेआउट समायोजित करने के लिए मॉड्यूल खींचें।' }, step4: { title: 'पूर्वावलोकन', content: 'वास्तविक समय में परिणाम देखें।' }, step5: { title: 'बनाएं', content: 'अपना उच्च गुणवत्ता कार्ड डाउनलोड करें।' } } },
    privacy: { title: 'गोपनीयता नीति', description: 'हम आपकी गोपनीयता की सुरक्षा कैसे करते हैं', lastUpdated: '10 जनवरी 2025', sections: { overview: { title: 'अवलोकन', content: 'हम आपकी गोपनीयता का सम्मान करते हैं और आपके डेटा की सुरक्षा करते हैं।' }, dataCollection: { title: 'संग्रह', content: 'स्थानीय प्रसंस्करण, कोई व्यक्तिगत डेटा अपलोड नहीं।' }, dataUsage: { title: 'उपयोग', content: 'सेवा सुधार के लिए केवल अज्ञात आंकड़े।' }, dataSecurity: { title: 'सुरक्षा', content: 'मानक डेटा सुरक्षा उपाय।' }, cookies: { title: 'कुकीज़', content: 'ब्राउज़िंग अनुभव सुधारने के लिए।' }, contact: { title: 'संपर्क', content: 'WeChat: skingko, प्रश्नों के लिए GitHub।' } } },
    terms: { title: 'सेवा की शर्तें', description: 'सेवा उपयोग की शर्तें', lastUpdated: '10 जनवरी 2025', sections: { acceptance: { title: 'स्वीकृति', content: 'सेवा का उपयोग करके, आप इन शर्तों को स्वीकार करते हैं।' }, usage: { title: 'उपयोग', content: 'सभी उपयोगकर्ताओं के लिए निःशुल्क सेवा।' }, content: { title: 'सामग्री', content: 'अपनी अपलोड की गई सामग्री के लिए जिम्मेदार।' }, limitation: { title: 'सीमा', content: 'कोई गारंटी नहीं, अपने जोखिम पर उपयोग।' }, modification: { title: 'संशोधन', content: 'हम आवश्यकता पड़ने पर सेवा को संशोधित कर सकते हैं।' }, contact: { title: 'संपर्क', content: 'WeChat: skingko, प्रश्नों के लिए GitHub।' } } },
    contact: { title: 'हमसे संपर्क करें', description: 'सहायता और समर्थन प्राप्त करें', methods: { wechat: { title: 'WeChat', description: 'ID: skingko तत्काल समर्थन के लिए।' }, github: { title: 'GitHub', description: 'मुद्दों और योगदान के लिए ओपन सोर्स प्रोजेक्ट।' }, email: { title: 'ईमेल', description: 'GitHub issues या चर्चाओं के माध्यम से संपर्क करें।' } } }
  }
}
