import { Translation } from '../types'

export const pt: Translation = {
  title: 'Gerador de Cartões de Redes Sociais',
  subtitle: 'Ferramenta de Design Profissional para Cartões Sociais',
  description: 'Crie belos cartões de redes sociais com vários temas e conteúdo personalizado',
  nav: { editContent: 'Editar Conteúdo', finishEdit: 'Finalizar Edição', generateImage: 'Gerar Imagem', generating: 'Gerando...', horizontal: 'Horizontal', vertical: 'Vertical', editMode: 'Modo de Edição' },
  themes: { blue: 'Azul Profissional', green: 'Verde Natureza', purple: 'Roxo Criativo', orange: 'Laranja Energético', red: 'Red Theme', yellow: 'Yellow Theme', black: 'Black Theme', pink: 'Rosa Elegante', dark: 'Escuro Moderno' },
  editor: {
    editContent: 'Edit Content',
    title: 'Title',
    subtitle: 'Subtitle',
    description: 'Description', name: 'Nome', title: 'Título', company: 'Empresa', phone: 'Telefone', email: 'Email', website: 'Site', wechat: 'WeChat', bio: 'Biografia', uploadQR: 'Carregar QR', features: 'Recursos' ,
    addFeature: 'Add Feature',
    qrCode: 'QR Code',
    dragUpload: 'Drag to upload',
    uploadSupport: 'PNG, JPG, GIF up to 10MB',
    uploading: 'Uploading...',
    qrUploaded: 'QR uploaded',
    clickRemove: 'Click to remove'
  },
  ui: { selectTheme: 'Selecionar Tema', layoutMode: 'Modo de Layout', previewEffect: 'Efeito de Visualização', collapsePreview: 'Recolher Visualização', expandPreview: 'Expandir Visualização', completeEditFirst: 'Por favor, complete a edição ou expanda a visualização antes de gerar a imagem', share: 'Compartilhar', shareToSocialMedia: 'Compartilhar nas Redes Sociais', copied: 'Copiado!', copyLink: 'Copiar Link', email: 'Email', cardNotFound: 'Elemento do cartão não encontrado, tente novamente', generateImageFailed: 'Falha na geração da imagem, tente novamente', selectValidImageFile: 'Selecione um arquivo de imagem válido' },
  footer: { developer: 'Desenvolvido por', githubRepo: 'Repositório GitHub', addAuthorWechat: 'Adicionar WeChat do Autor', wechatPublic: 'Conta Pública WeChat', scanToFollow: 'Escaneie para Seguir', scanToAdd: 'Escaneie para Adicionar', clickToEnlarge: 'Toque para Ampliar', hoverToEnlarge: 'Passe o mouse para Ampliar', websiteInfo: 'Informações do Site', domain: 'www.sm-card.com', websiteDescription: 'Gerador de Cartões de Redes Sociais' },
  defaultContent: { title: 'Desenvolvedor Full-Stack', subtitle: 'Especialista em Soluções Tecnológicas', description: 'Desenvolvedor apaixonado especializado em tecnologias modernas com rica experiência em desenvolvimento de aplicações web e móveis', feature1: 'Serviço Premium da Comunidade €1,4', feature2: 'Automação de Escritório a partir de €42', feature3: 'Serviço de Personalização de Software Negociável', feature4: 'Consultoria de Transformação Empresarial a partir de €140' },
  meta: { title: 'Gerador de Cartões de Redes Sociais - Ferramenta de Design Profissional', description: 'Gerador gratuito de cartões de redes sociais com múltiplos temas, ordenação por arrastar e soltar, visualização em tempo real e geração de cartões de alta qualidade com um clique', keywords: 'cartão redes sociais,gerador cartões,cartão social,design cartões,criador cartões,criador cartões online' },
  seo: {
    common: { backToHome: 'Voltar ao Início', lastUpdated: 'Última Atualização', getStarted: 'Começar', learnMore: 'Saber Mais', readyToStart: 'Pronto para começar?', startCreating: 'Começar a Criar', quickStart: 'Início Rápido', tipsAndTricks: 'Dicas e Truques', bestPractices: 'Melhores Práticas', commonFeatures: 'Recursos Comuns', stillHaveQuestions: 'Ainda tem dúvidas?', contactSupport: 'Contatar Suporte', followUs: 'Siga-nos', openSource: 'Código Aberto', projectIntroduction: 'Introdução ao Projeto', ourMission: 'Nossa Missão', features: 'Recursos', technologyStack: 'Stack Tecnológico', developmentTeam: 'Equipe de Desenvolvimento', contactUs: 'Contate-nos', websiteInfo: 'Informações do Site', legalNotice: 'Aviso Legal', dataProcessingDetails: 'Detalhes do Processamento de Dados', userRights: 'Seus Direitos', disclaimer: 'Isenção de Responsabilidade', legalJurisdiction: 'Jurisdição Legal', termsQuestions: 'Dúvidas sobre os Termos?', privacyQuestions: 'Dúvidas sobre Privacidade?', supportChannels: 'Canais de Suporte' },
    navigation: { about: 'Sobre Nós', faq: 'FAQ', guide: 'Guia do Usuário', privacy: 'Política de Privacidade', terms: 'Termos de Serviço', contact: 'Contato', sitemap: 'Mapa do Site' },
    about: { title: 'Sobre o Gerador de Cartões de Redes Sociais', description: 'Conheça nossa missão, equipe e tecnologia', content: { introduction: 'Ferramenta profissional online para criar cartões de redes sociais de alta qualidade.', mission: 'Permitir que todos criem facilmente cartões profissionais e bonitos.', features: 'Múltiplos estilos temáticos, arrastar e soltar, visualização em tempo real.', technology: 'Construído com Next.js, React, TypeScript e Tailwind CSS.', team: 'Equipe de desenvolvedores e designers experientes.', contact: 'Entre em contato conosco para dúvidas ou sugestões.' } },
    faq: { title: 'Perguntas Frequentes', description: 'Perguntas comuns sobre o Gerador de Cartões', questions: { q1: { question: 'Como usar o gerador?', answer: 'Escolha tema, preencha informações, arraste módulos, visualize e gere.' }, q2: { question: 'Quais idiomas são suportados?', answer: 'Mais de 20 idiomas incluindo português, inglês, chinês, japonês, etc.' }, q3: { question: 'Uso comercial possível?', answer: 'Sim, completamente gratuito para uso pessoal e comercial.' }, q4: { question: 'Como alterar o código QR?', answer: 'Editar, encontrar área de upload QR, carregar nova imagem.' }, q5: { question: 'Qualidade das imagens?', answer: 'Alta resolução, formato PNG com fundo transparente.' }, q6: { question: 'Registro necessário?', answer: 'Não, serviço gratuito sem necessidade de registro.' }, q7: { question: 'Segurança dos dados?', answer: 'Processamento local no seu navegador, máxima privacidade.' }, q8: { question: 'Suporte técnico?', answer: 'Contate via WeChat: skingko ou GitHub.' } } },
    guide: { title: 'Guia do Usuário', description: 'Aprenda a usar todos os recursos', steps: { step1: { title: 'Escolher Tema', content: 'Selecione entre vários estilos bonitos.' }, step2: { title: 'Preencher Informações', content: 'Insira suas informações pessoais e de contato.' }, step3: { title: 'Personalizar', content: 'Arraste módulos para ajustar o layout.' }, step4: { title: 'Visualizar', content: 'Veja o resultado em tempo real.' }, step5: { title: 'Gerar', content: 'Baixe seu cartão de alta qualidade.' } } },
    privacy: { title: 'Política de Privacidade', description: 'Como protegemos sua privacidade', lastUpdated: '10 de janeiro de 2025', sections: { overview: { title: 'Visão Geral', content: 'Respeitamos sua privacidade e protegemos seus dados.' }, dataCollection: { title: 'Coleta', content: 'Processamento local, sem upload de dados pessoais.' }, dataUsage: { title: 'Uso', content: 'Apenas estatísticas anônimas para melhorar o serviço.' }, dataSecurity: { title: 'Segurança', content: 'Medidas padrão de proteção de dados.' }, cookies: { title: 'Cookies', content: 'Para melhorar a experiência de navegação.' }, contact: { title: 'Contato', content: 'WeChat: skingko, GitHub para dúvidas.' } } },
    terms: { title: 'Termos de Serviço', description: 'Condições de uso do serviço', lastUpdated: '10 de janeiro de 2025', sections: { acceptance: { title: 'Aceitação', content: 'Ao usar o serviço, você aceita estes termos.' }, usage: { title: 'Uso', content: 'Serviço gratuito para todos os usuários.' }, content: { title: 'Conteúdo', content: 'Responsável pelo seu conteúdo carregado.' }, limitation: { title: 'Limitação', content: 'Sem garantias, uso por sua conta e risco.' }, modification: { title: 'Modificação', content: 'Podemos modificar o serviço se necessário.' }, contact: { title: 'Contato', content: 'WeChat: skingko, GitHub para dúvidas.' } } },
    contact: { title: 'Contate-nos', description: 'Obtenha ajuda e suporte', methods: { wechat: { title: 'WeChat', description: 'ID: skingko para suporte instantâneo.' }, github: { title: 'GitHub', description: 'Projeto de código aberto para issues e contribuições.' }, email: { title: 'Email', description: 'Contate via issues do GitHub ou discussões.' } } }  },
  poster: {
    clickToLearn: 'Clique para saber mais'
  }
}