import { Translation } from '../types'

export const th: Translation = {
  title: 'เครื่องมือสร้างบัตรโซเชียลมีเดีย',
  subtitle: 'เครื่องมือออกแบบบัตรโซเชียลระดับมืออาชีพ',
  description: 'สร้างบัตรโซเชียลมีเดียที่สวยงามด้วยธีมและเนื้อหาที่หลากหลาย',
  nav: { editContent: 'แก้ไขเนื้อหา', finishEdit: 'เสร็จสิ้นการแก้ไข', generateImage: 'สร้างรูปภาพ', generating: 'กำลังสร้าง...', horizontal: 'แนวนอน', vertical: 'แนวตั้ง', editMode: 'โหมดแก้ไข' },
  themes: { blue: 'สีน้ำเงินมืออาชีพ', green: 'สีเขียวธรรมชาติ', purple: 'สีม่วงสร้างสรรค์', orange: 'สีส้มกระปี้กระเป่า', red: 'Red Theme', yellow: 'Yellow Theme', black: 'Black Theme', pink: 'สีชมพูสง่างาม', dark: 'สีเข้มทันสมัย' },
  editor: {
    editContent: 'Edit Content',
    title: 'Title',
    subtitle: 'Subtitle',
    description: 'คำอธิบาย',
    name: 'ชื่อ',
    company: 'บริษัท',
    phone: 'โทรศัพท์',
    email: 'อีเมล',
    website: 'เว็บไซต์',
    wechat: 'WeChat',
    bio: 'ประวัติย่อ',
    features: 'คุณสมบัติ',
    addFeature: 'Add Feature',
    qrCode: 'QR Code',
    dragUpload: 'Drag to upload',
    uploadSupport: 'PNG, JPG, GIF up to 10MB',
    uploading: 'Uploading...',
    qrUploaded: 'QR uploaded',
    clickRemove: 'Click to remove'
  },
  ui: { selectTheme: 'เลือกธีม', layoutMode: 'โหมดเลย์เอาต์', previewEffect: 'เอฟเฟกต์ตัวอย่าง', collapsePreview: 'ยุบตัวอย่าง', expandPreview: 'ขยายตัวอย่าง', completeEditFirst: 'กรุณาแก้ไขให้เสร็จสิ้นหรือขยายตัวอย่างก่อนสร้างรูปภาพ', share: 'แชร์', shareToSocialMedia: 'แชร์ในโซเชียลมีเดีย', copied: 'คัดลอกแล้ว!', copyLink: 'คัดลอกลิงก์', email: 'อีเมล', cardNotFound: 'ไม่พบองค์ประกอบบัตร กรุณาลองใหม่', generateImageFailed: 'สร้างรูปภาพไม่สำเร็จ กรุณาลองใหม่', selectValidImageFile: 'กรุณาเลือกไฟล์รูปภาพที่ถูกต้อง' },
  footer: { developer: 'พัฒนาโดย', github: 'GitHub', wechat: 'WeChat', followUs: 'ติดตามเรา', author: 'ผู้เขียน', githubRepo: 'GitHub Repository', addAuthorWechat: 'เพิ่ม WeChat ผู้เขียน', wechatPublic: 'บัญชีสาธารณะ WeChat', scanToFollow: 'สแกนเพื่อติดตาม', scanToAdd: 'สแกนเพื่อเพิ่ม', clickToEnlarge: 'แตะเพื่อขยาย', hoverToEnlarge: 'เลื่อนเพื่อขยาย', websiteInfo: 'ข้อมูลเว็บไซต์', domain: 'www.sm-card.com', websiteDescription: 'เครื่องมือสร้างบัตรโซเชียลมีเดีย' },
  defaultContent: { title: 'นักพัฒนา Full-Stack', subtitle: 'ผู้เชี่ยวชาญโซลูชันเทคโนโลยี', description: 'นักพัฒนาที่หลงใหลเชี่ยวชาญด้านเทคโนโลยีสมัยใหม่ มีประสบการณ์มากมายในการพัฒนาแอปพลิเคชันเว็บและมือถือ', feature1: 'บริการชุมชนพรีเมียม €1.4', feature2: 'ระบบอัตโนมัติสำนักงานเริ่มต้น €42', feature3: 'บริการปรับแต่งซอฟต์แวร์ตามต้องการ', feature4: 'คำปรึกษาการเปลี่ยนแปลงองค์กรเริ่มต้น €140' },
  meta: { title: 'เครื่องมือสร้างบัตรโซเชียลมีเดีย - เครื่องมือออกแบบระดับมืออาชีพ', description: 'เครื่องมือสร้างบัตรโซเชียลมีเดียฟรี พร้อมธีมหลากหลาย การจัดเรียงแบบลากและวาง ตัวอย่างแบบเรียลไทม์ และการสร้างบัตรคุณภาพสูงด้วยการคลิกเดียว', keywords: 'บัตรโซเชียลมีเดีย,เครื่องมือสร้างบัตร,บัตรโซเชียล,ออกแบบบัตร,สร้างบัตร,สร้างบัตรออนไลน์' },
  seo: {
    common: { backToHome: 'กลับหน้าแรก', lastUpdated: 'อัปเดตล่าสุด', getStarted: 'เริ่มต้น', learnMore: 'เรียนรู้เพิ่มเติม', readyToStart: 'พร้อมเริ่มต้นหรือยัง?', startCreating: 'เริ่มสร้างเลย', quickStart: 'เริ่มต้นอย่างรวดเร็ว', tipsAndTricks: 'เคล็ดลับและเทคนิค', bestPractices: 'แนวปฏิบัติที่ดีที่สุด', commonFeatures: 'คุณสมบัติทั่วไป', stillHaveQuestions: 'ยังมีคำถามอีกไหม?', contactSupport: 'ติดต่อฝ่ายสนับสนุน', followUs: 'ติดตามเรา', openSource: 'โอเพ่นซอร์ส', projectIntroduction: 'แนะนำโครงการ', ourMission: 'ภารกิจของเรา', features: 'คุณสมบัติ', technologyStack: 'เทคโนโลยีสแต็ก', developmentTeam: 'ทีมพัฒนา', contactUs: 'ติดต่อเรา', websiteInfo: 'ข้อมูลเว็บไซต์', legalNotice: 'ประกาศทางกฎหมาย', dataProcessingDetails: 'รายละเอียดการประมวลผลข้อมูล', userRights: 'สิทธิ์ของคุณ', disclaimer: 'ข้อจำกัดความรับผิดชอบ', legalJurisdiction: 'เขตอำนาจศาลทางกฎหมาย', termsQuestions: 'มีคำถามเกี่ยวกับข้อกำหนด?', privacyQuestions: 'คำถามด้านความเป็นส่วนตัว?', supportChannels: 'ช่องทางสนับสนุน' },
    navigation: { about: 'เกี่ยวกับเรา', faq: 'คำถามที่พบบ่อย', guide: 'คู่มือผู้ใช้', privacy: 'นโยบายความเป็นส่วนตัว', terms: 'เงื่อนไขการใช้บริการ', contact: 'ติดต่อ', sitemap: 'แผนผังเว็บไซต์' },
    about: { title: 'เกี่ยวกับเครื่องมือสร้างบัตรโซเชียลมีเดีย', description: 'เรียนรู้เกี่ยวกับภารกิจ ทีม และเทคโนโลยีของเรา', content: { introduction: 'เครื่องมือออนไลน์ระดับมืออาชีพสำหรับสร้างบัตรโซเชียลมีเดียคุณภาพสูง', mission: 'ทำให้ทุกคนสามารถสร้างบัตรที่สวยงามและเป็นมืออาชีพได้อย่างง่ายดาย', features: 'ธีมสไตล์หลากหลาย ลากและวาง ตัวอย่างแบบเรียลไทม์', technology: 'สร้างด้วย Next.js, React, TypeScript และ Tailwind CSS', team: 'ทีมนักพัฒนาและนักออกแบบที่มีประสบการณ์', contact: 'ติดต่อเราสำหรับคำถามหรือข้อเสนอแนะ' }, featureList: { multiTheme: { title: 'ธีมหลากสไตล์', description: 'เสนอธีมสวยงามหลากหลายสำหรับสถานการณ์ต่างๆ' }, dragSort: { title: 'จัดเรียงแบบลาก', description: 'ปรับลำดับการแสดงผลของโมดูลคุณสมบัติได้อย่างอิสระ' }, realTimePreview: { title: 'ตัวอย่างแบบเรียลไทม์', description: 'ประสบการณ์การแก้ไข WYSIWYG' }, multiLanguage: { title: 'รองรับหลายภาษา', description: 'รองรับมากกว่า 20 ภาษา ให้บริการผู้ใช้ทั่วโลก' }, highQuality: { title: 'ผลลัพธ์คุณภาพสูง', description: 'สร้างภาพบัตรความละเอียดสูงด้วยการคลิกเดียว' }, completelyFree: { title: 'ฟรีทั้งหมด', description: 'คุณสมบัติทั้งหมดใช้งานฟรี ไม่ต้องลงทะเบียน' } } },
    faq: { title: 'คำถามที่พบบ่อย', description: 'คำถามทั่วไปเกี่ยวกับเครื่องมือสร้างบัตร', moreQuestions: 'มีคำถามอื่นๆ อีกไหม?', contactSupport: 'หากไม่พบคำตอบ กรุณาติดต่อทีมสนับสนุนทางเทคนิคของเราโดยตรง', questions: { q1: { question: 'วิธีใช้เครื่องมือสร้าง?', answer: 'เลือกธีม กรอกข้อมูล ลากโมดูล ดูตัวอย่างและสร้าง' }, q2: { question: 'รองรับภาษาใดบ้าง?', answer: 'รองรับมากกว่า 20 ภาษา รวมถึงไทย อังกฤษ จีน ญี่ปุ่น เป็นต้น' }, q3: { question: 'ใช้เชิงพาณิชย์ได้หรือไม่?', answer: 'ได้ ฟรีสำหรับการใช้งานส่วนบุคคลและเชิงพาณิชย์' }, q4: { question: 'วิธีเปลี่ยน QR Code?', answer: 'แก้ไข หาพื้นที่อัปโหลด QR อัปโหลดรูปใหม่' }, q5: { question: 'คุณภาพของรูปภาพ?', answer: 'ความละเอียดสูง รูปแบบ PNG พร้อมพื้นหลังโปร่งใส' }, q6: { question: 'ต้องลงทะเบียนหรือไม่?', answer: 'ไม่ต้อง บริการฟรีไม่ต้องลงทะเบียน' }, q7: { question: 'ความปลอดภัยของข้อมูล?', answer: 'ประมวลผลในเครื่องของคุณ ความเป็นส่วนตัวสูงสุด' }, q8: { question: 'การสนับสนุนทางเทคนิค?', answer: 'ติดต่อผ่าน WeChat: skingko หรือ GitHub' } } },
    guide: { title: 'คู่มือผู้ใช้', description: 'เรียนรู้การใช้คุณสมบัติทั้งหมด', simpleSteps: 'เพียง 5 ขั้นตอนง่ายๆ เพื่อสร้างบัตรโซเชียลมีเดียระดับมืออาชีพ:', startCreatingNow: 'เริ่มสร้างบัตรโซเชียลมีเดียระดับมืออาชีพของคุณเดี๋ยวนี้เลย!', steps: { step1: { title: 'เลือกธีม', content: 'เลือกจากสไตล์สวยงามหลากหลาย' }, step2: { title: 'กรอกข้อมูล', content: 'ใส่ข้อมูลส่วนตัวและการติดต่อ' }, step3: { title: 'ปรับแต่ง', content: 'ลากโมดูลเพื่อปรับเลย์เอาต์' }, step4: { title: 'ดูตัวอย่าง', content: 'ดูผลลัพธ์แบบเรียลไทม์' }, step5: { title: 'สร้าง', content: 'ดาวน์โหลดบัตรคุณภาพสูงของคุณ' } } },
    privacy: { title: 'นโยบายความเป็นส่วนตัว', description: 'วิธีที่เราปกป้องความเป็นส่วนตัวของคุณ', lastUpdated: '10 มกราคม 2025', privacyCommitment: 'ข้อผูกพันด้านความเป็นส่วนตัว', privacyCommitmentText: 'เราให้ความเป็นส่วนตัวเป็นสิ่งสำคัญและผูกพันที่จะปกป้องข้อมูลทั้งหมดอย่างปลอดภัย', dataProcessingDetails: 'รายละเอียดการประมวลผลข้อมูล', yourRights: 'สิทธิ์ของคุณ', contactRightText: 'หากคุณมีคำถามหรือคำขอเกี่ยวกับความเป็นส่วนตัว กรุณาติดต่อเราได้ตลอดเวลา', privacyQuestionsTitle: 'คำถามด้านความเป็นส่วนตัว?', privacyQuestionsText: 'หากคุณมีคำถามเกี่ยวกับนโยบายความเป็นส่วนตัวของเรา กรุณาติดต่อเรา', sections: { overview: { title: 'ภาพรวม', content: 'เราเคารพความเป็นส่วนตัวและปกป้องข้อมูลของคุณ' }, dataCollection: { title: 'การเก็บข้อมูล', content: 'ประมวลผลในเครื่อง ไม่อัปโหลดข้อมูลส่วนบุคคล' }, dataUsage: { title: 'การใช้งาน', content: 'เฉพาะสถิติไม่ระบุตัวตนเพื่อปรับปรุงบริการ' }, dataSecurity: { title: 'ความปลอดภัย', content: 'มาตรการปกป้องข้อมูลมาตรฐาน' }, cookies: { title: 'คุกกี้', content: 'เพื่อปรับปรุงประสบการณ์การใช้งาน' }, contact: { title: 'ติดต่อ', content: 'WeChat: skingko, GitHub สำหรับคำถาม' } } },
    terms: { title: 'เงื่อนไขการใช้บริการ', description: 'เงื่อนไขการใช้บริการ', lastUpdated: '10 มกราคม 2025', termsQuestionsTitle: 'มีคำถามเกี่ยวกับข้อกำหนด?', termsQuestionsText: 'หากคุณมีคำถามเกี่ยวกับเงื่อนไขการใช้บริการของเรา กรุณาติดต่อเรา', sections: { acceptance: { title: 'การยอมรับ', content: 'การใช้บริการหมายถึงคุณยอมรับเงื่อนไขเหล่านี้' }, usage: { title: 'การใช้งาน', content: 'บริการฟรีสำหรับผู้ใช้ทุกคน' }, content: { title: 'เนื้อหา', content: 'รับผิดชอบต่อเนื้อหาที่อัปโหลด' }, limitation: { title: 'ข้อจำกัด', content: 'ไม่มีการรับประกัน ใช้ความเสี่ยงของตัวเอง' }, modification: { title: 'การแก้ไข', content: 'เราอาจแก้ไขบริการเมื่อจำเป็น' }, contact: { title: 'ติดต่อ', content: 'WeChat: skingko, GitHub สำหรับคำถาม' } } },
    contact: { title: 'ติดต่อเรา', description: 'รับความช่วยเหลือและการสนับสนุน', methods: { wechat: { title: 'WeChat', description: 'ID: skingko สำหรับการสนับสนุนทันที' }, github: { title: 'GitHub', description: 'โปรเจกต์โอเพ่นซอร์สสำหรับปัญหาและการมีส่วนร่วม' }, email: { title: 'อีเมล', description: 'ติดต่อผ่าน GitHub issues หรือการสนทนา' } } }  },
  poster: {
    clickToLearn: 'คลิกเพื่อเรียนรู้'
  }
}