import { Translation } from '../types'

export const vi: Translation = {
  title: 'Trình Tạo Thẻ Mạng Xã Hội',
  subtitle: 'Công Cụ Thiết Kế Thẻ Xã Hội Chuyên Nghiệp',
  description: 'Tạo thẻ mạng xã hội đẹp với các chủ đề đa dạng và nội dung tùy chỉnh',
  nav: { editContent: 'Chỉnh Sửa Nội Dung', finishEdit: 'Hoàn Thành Chỉnh Sửa', generateImage: 'Tạo Hình Ảnh', generating: 'Đang Tạo...', horizontal: 'Ngang', vertical: 'Dọc', editMode: 'Chế Độ Chỉnh Sửa' },
  themes: { blue: 'Xanh Dương Chuyên Nghiệp', green: 'Xanh Lá Tự Nhiên', purple: 'Tím Sáng Tạo', orange: 'Cam Năng Động', red: 'Red Theme', yellow: 'Yellow Theme', black: 'Black Theme', pink: 'Hồng Thanh Lịch', dark: 'Tối Hiện Đại' },
  editor: {
    editContent: 'Edit Content',
    title: 'Title',
    subtitle: 'Subtitle',
    description: 'Description', name: 'Tên', title: 'Tiêu Đề', company: 'Công Ty', phone: 'Điện Thoại', email: 'Email', website: 'Trang Web', wechat: 'WeChat', bio: 'Tiểu Sử', uploadQR: 'Tải Lên QR', features: 'Tính Năng' ,
    addFeature: 'Add Feature',
    qrCode: 'QR Code',
    dragUpload: 'Drag to upload',
    uploadSupport: 'PNG, JPG, GIF up to 10MB',
    uploading: 'Uploading...',
    qrUploaded: 'QR uploaded',
    clickRemove: 'Click to remove'
  },
  ui: { selectTheme: 'Chọn Chủ Đề', layoutMode: 'Chế Độ Bố Cục', previewEffect: 'Hiệu Ứng Xem Trước', collapsePreview: 'Thu Gọn Xem Trước', expandPreview: 'Mở Rộng Xem Trước', completeEditFirst: 'Vui lòng hoàn thành chỉnh sửa hoặc mở rộng xem trước trước khi tạo hình ảnh', share: 'Chia Sẻ', shareToSocialMedia: 'Chia Sẻ Trên Mạng Xã Hội', copied: 'Đã Sao Chép!', copyLink: 'Sao Chép Liên Kết', email: 'Email', cardNotFound: 'Không tìm thấy phần tử thẻ, vui lòng thử lại', generateImageFailed: 'Tạo hình ảnh thất bại, vui lòng thử lại', selectValidImageFile: 'Vui lòng chọn tệp hình ảnh hợp lệ' },
  footer: { developer: 'Được Phát Triển Bởi', githubRepo: 'Kho GitHub', addAuthorWechat: 'Thêm WeChat Tác Giả', wechatPublic: 'Tài Khoản Công Khai WeChat', scanToFollow: 'Quét Để Theo Dõi', scanToAdd: 'Quét Để Thêm', clickToEnlarge: 'Chạm Để Phóng To', hoverToEnlarge: 'Di Chuột Để Phóng To', websiteInfo: 'Thông Tin Trang Web', domain: 'www.sm-card.com', websiteDescription: 'Trình Tạo Thẻ Mạng Xã Hội' },
  defaultContent: { title: 'Lập Trình Viên Full-Stack', subtitle: 'Chuyên Gia Giải Pháp Công Nghệ', description: 'Lập trình viên đam mê chuyên về công nghệ hiện đại với kinh nghiệm phong phú trong phát triển ứng dụng web và di động', feature1: 'Dịch Vụ Cộng Đồng Cao Cấp €1,4', feature2: 'Tự Động Hóa Văn Phòng từ €42', feature3: 'Dịch Vụ Tùy Chỉnh Phần Mềm Có Thể Thương Lượng', feature4: 'Tư Vấn Chuyển Đổi Doanh Nghiệp từ €140' },
  meta: { title: 'Trình Tạo Thẻ Mạng Xã Hội - Công Cụ Thiết Kế Chuyên Nghiệp', description: 'Trình tạo thẻ mạng xã hội miễn phí với nhiều chủ đề, sắp xếp kéo thả, xem trước thời gian thực và tạo thẻ chất lượng cao chỉ với một cú nhấp chuột', keywords: 'thẻ mạng xã hội,trình tạo thẻ,thẻ xã hội,thiết kế thẻ,tạo thẻ,tạo thẻ trực tuyến' },
  seo: {
    common: { backToHome: 'Về Trang Chủ', lastUpdated: 'Cập Nhật Lần Cuối', getStarted: 'Bắt Đầu', learnMore: 'Tìm Hiểu Thêm', readyToStart: 'Sẵn sàng bắt đầu?', startCreating: 'Bắt Đầu Tạo Ngay', quickStart: 'Khởi Động Nhanh', tipsAndTricks: 'Mẹo Và Thủ Thuật', bestPractices: 'Thực Hành Tốt Nhất', commonFeatures: 'Tính Năng Phổ Biến', stillHaveQuestions: 'Vẫn có câu hỏi?', contactSupport: 'Liên Hệ Hỗ Trợ', followUs: 'Theo Dõi Chúng Tôi', openSource: 'Mã Nguồn Mở', projectIntroduction: 'Giới Thiệu Dự Án', ourMission: 'Sứ Mệnh Của Chúng Tôi', features: 'Tính Năng', technologyStack: 'Ngăn Xếp Công Nghệ', developmentTeam: 'Đội Phát Triển', contactUs: 'Liên Hệ Với Chúng Tôi', websiteInfo: 'Thông Tin Trang Web', legalNotice: 'Thông Báo Pháp Lý', dataProcessingDetails: 'Chi Tiết Xử Lý Dữ Liệu', userRights: 'Quyền Của Bạn', disclaimer: 'Từ Chối Trách Nhiệm', legalJurisdiction: 'Thẩm Quyền Pháp Lý', termsQuestions: 'Câu Hỏi Về Điều Khoản?', privacyQuestions: 'Câu Hỏi Về Quyền Riêng Tư?', supportChannels: 'Kênh Hỗ Trợ' },
    navigation: { about: 'Về Chúng Tôi', faq: 'Câu Hỏi Thường Gặp', guide: 'Hướng Dẫn Người Dùng', privacy: 'Chính Sách Bảo Mật', terms: 'Điều Khoản Dịch Vụ', contact: 'Liên Hệ', sitemap: 'Sơ Đồ Trang Web' },
    about: { title: 'Về Trình Tạo Thẻ Mạng Xã Hội', description: 'Tìm hiểu về sứ mệnh, đội ngũ và công nghệ của chúng tôi', content: { introduction: 'Công cụ trực tuyến chuyên nghiệp để tạo thẻ mạng xã hội chất lượng cao.', mission: 'Giúp mọi người dễ dàng tạo ra những thẻ đẹp và chuyên nghiệp.', features: 'Nhiều phong cách chủ đề, kéo thả, xem trước thời gian thực.', technology: 'Được xây dựng bằng Next.js, React, TypeScript và Tailwind CSS.', team: 'Đội ngũ lập trình viên và thiết kế viên giàu kinh nghiệm.', contact: 'Liên hệ với chúng tôi để được giải đáp thắc mắc hoặc đóng góp ý kiến.' } },
    faq: { title: 'Câu Hỏi Thường Gặp', description: 'Các câu hỏi phổ biến về Trình Tạo Thẻ', questions: { q1: { question: 'Cách sử dụng trình tạo?', answer: 'Chọn chủ đề, điền thông tin, kéo các module, xem trước và tạo.' }, q2: { question: 'Hỗ trợ ngôn ngữ nào?', answer: 'Hỗ trợ hơn 20 ngôn ngữ bao gồm tiếng Việt, tiếng Anh, tiếng Trung, tiếng Nhật, v.v.' }, q3: { question: 'Có thể sử dụng thương mại?', answer: 'Có, hoàn toàn miễn phí cho cả mục đích cá nhân và thương mại.' }, q4: { question: 'Cách thay đổi mã QR?', answer: 'Chỉnh sửa, tìm khu vực tải lên QR, tải lên hình ảnh mới.' }, q5: { question: 'Chất lượng hình ảnh?', answer: 'Độ phân giải cao, định dạng PNG với nền trong suốt.' }, q6: { question: 'Cần đăng ký không?', answer: 'Không, dịch vụ miễn phí không cần đăng ký.' }, q7: { question: 'Bảo mật dữ liệu?', answer: 'Xử lý cục bộ trong trình duyệt của bạn, bảo mật tối đa.' }, q8: { question: 'Hỗ trợ kỹ thuật?', answer: 'Liên hệ qua WeChat: skingko hoặc GitHub.' } } },
    guide: { title: 'Hướng Dẫn Người Dùng', description: 'Học cách sử dụng tất cả các tính năng', steps: { step1: { title: 'Chọn Chủ Đề', content: 'Chọn từ nhiều phong cách đẹp mắt.' }, step2: { title: 'Điền Thông Tin', content: 'Nhập thông tin cá nhân và liên hệ của bạn.' }, step3: { title: 'Tùy Chỉnh', content: 'Kéo các module để điều chỉnh bố cục.' }, step4: { title: 'Xem Trước', content: 'Xem kết quả trong thời gian thực.' }, step5: { title: 'Tạo', content: 'Tải xuống thẻ chất lượng cao của bạn.' } } },
    privacy: { title: 'Chính Sách Bảo Mật', description: 'Cách chúng tôi bảo vệ quyền riêng tư của bạn', lastUpdated: '10 tháng 1, 2025', sections: { overview: { title: 'Tổng Quan', content: 'Chúng tôi tôn trọng quyền riêng tư và bảo vệ dữ liệu của bạn.' }, dataCollection: { title: 'Thu Thập', content: 'Xử lý cục bộ, không tải lên dữ liệu cá nhân.' }, dataUsage: { title: 'Sử Dụng', content: 'Chỉ thống kê ẩn danh để cải thiện dịch vụ.' }, dataSecurity: { title: 'Bảo Mật', content: 'Các biện pháp bảo vệ dữ liệu tiêu chuẩn.' }, cookies: { title: 'Cookie', content: 'Để cải thiện trải nghiệm duyệt web.' }, contact: { title: 'Liên Hệ', content: 'WeChat: skingko, GitHub cho các câu hỏi.' } } },
    terms: { title: 'Điều Khoản Dịch Vụ', description: 'Điều kiện sử dụng dịch vụ', lastUpdated: '10 tháng 1, 2025', sections: { acceptance: { title: 'Chấp Nhận', content: 'Bằng cách sử dụng dịch vụ, bạn đồng ý với các điều khoản này.' }, usage: { title: 'Sử Dụng', content: 'Dịch vụ miễn phí cho tất cả người dùng.' }, content: { title: 'Nội Dung', content: 'Chịu trách nhiệm về nội dung bạn tải lên.' }, limitation: { title: 'Giới Hạn', content: 'Không có bảo đảm, sử dụng với rủi ro của riêng bạn.' }, modification: { title: 'Sửa Đổi', content: 'Chúng tôi có thể sửa đổi dịch vụ khi cần thiết.' }, contact: { title: 'Liên Hệ', content: 'WeChat: skingko, GitHub cho các câu hỏi.' } } },
    contact: { title: 'Liên Hệ Với Chúng Tôi', description: 'Nhận trợ giúp và hỗ trợ', methods: { wechat: { title: 'WeChat', description: 'ID: skingko cho hỗ trợ tức thì.' }, github: { title: 'GitHub', description: 'Dự án mã nguồn mở cho vấn đề và đóng góp.' }, email: { title: 'Email', description: 'Liên hệ qua GitHub issues hoặc thảo luận.' } } }  },
  poster: {
    clickToLearn: 'Nhấp để tìm hiểu'
  }
}